# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photocatalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photocatalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12photocatalog.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\tIdRequest\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x05\n\x03_id\",\n\x0c\x43ountRequest\x12\x12\n\x05\x63ount\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\x08\n\x06_count\"Z\n\x0cPhotoRequest\x12\x18\n\x0b\x64\x65scription\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_descriptionB\n\n\x08_content\"\xb5\x01\n\rPhotoResponse\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x32\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x05\n\x03_idB\x0e\n\x0c_descriptionB\x0c\n\n_timestampB\n\n\x08_content\"p\n\x14UploadStatusResponse\x12\x14\n\x07success\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x0cuploaded_ids\x18\x03 \x03(\tB\n\n\x08_successB\n\n\x08_message2\xcb\x01\n\x13PhotoCatalogService\x12#\n\x05Photo\x12\n.IdRequest\x1a\x0e.PhotoResponse\x12)\n\x08\x41\x64\x64Photo\x12\r.PhotoRequest\x1a\x0e.PhotoResponse\x12/\n\x0cRandomPhotos\x12\r.CountRequest\x1a\x0e.PhotoResponse0\x01\x12\x33\n\tAddPhotos\x12\r.PhotoRequest\x1a\x15.UploadStatusResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photocatalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDREQUEST']._serialized_start=55
  _globals['_IDREQUEST']._serialized_end=90
  _globals['_COUNTREQUEST']._serialized_start=92
  _globals['_COUNTREQUEST']._serialized_end=136
  _globals['_PHOTOREQUEST']._serialized_start=138
  _globals['_PHOTOREQUEST']._serialized_end=228
  _globals['_PHOTORESPONSE']._serialized_start=231
  _globals['_PHOTORESPONSE']._serialized_end=412
  _globals['_UPLOADSTATUSRESPONSE']._serialized_start=414
  _globals['_UPLOADSTATUSRESPONSE']._serialized_end=526
  _globals['_PHOTOCATALOGSERVICE']._serialized_start=529
  _globals['_PHOTOCATALOGSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)